---
apiVersion: v1
kind: Service
metadata:
  name: chromadb
  annotations:
    zarf.dev/connect-description: "Access the vector db to retrieve contexts."
    zarf.dev/connect-url: "?chromadb"
  labels:
    zarf.dev/connect-name: chromadb
spec:
  selector:
    app: chromadb
  ports:
    - name: http
      port: 8000
      protocol: TCP
      targetPort: 8000
